input:
  schema: # for schema validation only
    document:
      type: object
      description: ollama input
      properties:
        prompt:
          type: string
          description: "The initial prompt."
        sample_len:
          description: "The length of the sample to generate (in tokens) (default: context size)."
          type: integer
        temperature:
          description: "The temperature used to generate samples."
          type: number
        top_p:
          description: "Nucleus sampling probability cutoff."
          type: number
        repeat_penalty:
          description: "Penalty to be applied for repeating tokens, 1. means no penalty."
          type: number
        repeat_last_n:
          description: "The context size to consider for the repeat penalty."
          type: integer
        seed:
          description: "The seed to use when generating random samples."
          type: integer
      required: [prompt]
output: # for annotation only
  schema:
    document:
      type: object
      description: ollama output
      properties:
        prompt:
          type: string
          description: "The initial prompt."
        sample_len:
          type: integer
          description: "The length of the sample to generate (in tokens) (default: context size)."
        temperature:
          description: "The temperature used to generate samples."
          type: number
        top_p:
          description: "Nucleus sampling probability cutoff."
          type: number
        repeat_penalty:
          description: "Penalty to be applied for repeating tokens, 1. means no penalty."
          type: number
        repeat_last_n:
          description: "The context size to consider for the repeat penalty."
          type: integer
        seed:
          description: "The seed to use when generating random samples."
          type: integer
run:
  script:
    language: jobworkerp
    code: OllamaPromptRunner
    arguments: # for annotation only
      prompt: |
        ${.}
metadata: # todo init parameters
  runnerSettings:
    baseUrl: http://localhost:11434
    model: # specify the model to use (string)
    systemPrompt: # specify the system prompt to use (string)
  worker:
    name: OllamaWorker # temporary name

