// Reranker Runner - llama.cpp-based reranker plugin for JobworkerP
//
// This module provides high-performance document reranking using llama.cpp
// and Qwen3-Reranker-4B-GGUF model, achieving 100-250x speedup over
// the existing Candle-based implementation.

use anyhow::{Result, anyhow};
use host_proto::jobworkerp::data::{MethodJsonSchema, MethodSchema, StreamingOutputType};
use jobworkerp_plugin_abi::v2::{CancelToken, HighLevelSink, PluginV2};
use jobworkerp_plugin_abi_macros::register_plugin_v2;
use prost::Message;
use std::{collections::HashMap, io::Cursor, sync::Arc, time::Instant};

/// Serialize a `schemars::JsonSchema` type into a JSON string for the
/// `MethodJsonSchema` / settings_schema slots.
fn json_schema_string<T: schemars::JsonSchema>(label: &str) -> String {
    let schema = schemars::schema_for!(T);
    match serde_json::to_string(&schema) {
        Ok(s) => s,
        Err(e) => {
            tracing::error!("error in {label}: {e:?}");
            String::new()
        }
    }
}

// Shared components (copied from search-runner)
pub mod cache;
pub mod traits;
pub mod utils;

// Core components
pub mod config;
pub mod error;
pub mod model;
pub mod reranker;

// Protocol Buffers (generated by build.rs)
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/reranker_runner.rs"));
}

// Re-export commonly used types
pub use cache::RerankerCache;
pub use config::{RerankerConfig, RerankerModelConfig};
pub use error::RerankerError;
pub use model::LlamaRerankerModel;
pub use reranker::{LlamaReranker, ScoringResult, ScoringStats};
pub use traits::{DocumentReranker, RerankerOptions};
pub use utils::{blend_scores, generate_cache_key};

use proto::{RerankerArgs, RerankerResult, RerankerSettings};

pub const METHOD_RUN: &str = "run";

/// Error-string surface for cooperative cancellation, shared with the host's
/// cancellation contract. Callers may match against this exact string.
pub const CANCELLED: &str = "cancelled";

/// RerankerRunner Plugin for JobworkerP
///
/// This plugin provides document reranking functionality using llama.cpp
/// and Qwen3-Reranker-4B-GGUF model.
pub struct RerankerRunnerPlugin {
    /// Plugin-owned multi-thread tokio runtime. Held in `Option` so `Drop`
    /// can `shutdown_background()` instead of blocking the calling thread —
    /// the latter panics when invoked from inside another async context
    /// (e.g. when the host drops the plugin from a `tokio::test`).
    rt: Option<tokio::runtime::Runtime>,
    /// Shared so it can be cloned into the spawn closure.
    /// `compute_scores_with_stats` is `&self`, and all interior state lives
    /// behind its own synchronization (cache LRU, llama.cpp model lock), so a
    /// plain `Arc` is enough.
    reranker: Option<Arc<LlamaReranker>>,
    /// Configuration
    config: Option<RerankerConfig>,
    /// Refreshed before each job via `set_cancellation_token`. Threaded into
    /// `compute_scores_with_stats` so the inner per-document loop aborts
    /// promptly.
    token: Option<CancelToken>,
}

impl RerankerRunnerPlugin {
    pub const RUNNER_NAME: &str = "RerankerRunner";

    pub fn new() -> Self {
        let rt = tokio::runtime::Builder::new_multi_thread()
            .worker_threads(2)
            .enable_all()
            .thread_name("reranker-runner-plugin")
            .build()
            .expect("Failed to build plugin tokio runtime");
        Self {
            rt: Some(rt),
            reranker: None,
            config: None,
            token: None,
        }
    }

    fn rt_handle(&self) -> tokio::runtime::Handle {
        self.rt
            .as_ref()
            .expect("plugin runtime accessed after Drop")
            .handle()
            .clone()
    }
}

impl Drop for RerankerRunnerPlugin {
    fn drop(&mut self) {
        if let Some(rt) = self.rt.take() {
            rt.shutdown_background();
        }
    }
}

impl RerankerRunnerPlugin {
    /// Parse Protobuf RerankerSettings into RerankerConfig
    fn parse_settings(settings: RerankerSettings) -> Result<RerankerConfig> {
        let model = RerankerModelConfig {
            model_id: settings.model_id,
            hf_repo: settings.hf_repo.unwrap_or_default(),
            use_cpu: settings.use_cpu,
            threads: settings.threads.map(|t| t as usize).unwrap_or(4),
            ctx_size: settings.ctx_size.map(|c| c as usize).unwrap_or(32768),
            n_batch: settings.n_batch.map(|b| b as usize).unwrap_or(32768),
            use_flash_attention: settings.use_flash_attention.unwrap_or(true),
            default_instruction: settings.default_instruction,
            max_document_length_gpu: settings
                .max_document_length_gpu
                .map(|m| m as usize)
                .unwrap_or(20_000),
            max_document_length_cpu: settings
                .max_document_length_cpu
                .map(|m| m as usize)
                .unwrap_or(5_000),
        };

        Ok(RerankerConfig {
            model,
            cache_size: settings.cache_size.map(|c| c as usize).unwrap_or(10_000),
            cache_ttl_seconds: settings.cache_ttl_seconds.unwrap_or(3600),
        })
    }

    /// Parse Protobuf RerankerArgs into (query, documents, options)
    fn parse_args(args: &RerankerArgs) -> Result<(String, Vec<String>, RerankerOptions)> {
        let query = args.query.clone();

        if query.is_empty() {
            return Err(anyhow!("Query is empty"));
        }

        // Extract text from candidates
        let documents: Vec<String> = args.candidates.iter().map(|c| c.text.clone()).collect();

        if documents.is_empty() {
            return Err(anyhow!("No candidates provided"));
        }

        // Parse options
        let options = if let Some(opts) = &args.options {
            RerankerOptions {
                top_k: opts.top_k.map(|k| k as usize),
                score_threshold: opts.score_threshold,
                instruction: opts.instruction.clone(),
                batch_size: opts.batch_size.map(|b| b as usize).unwrap_or(1),
                use_cache: opts.use_cache.unwrap_or(true),
                max_document_length: opts.max_document_length.map(|m| m as usize),
            }
        } else {
            RerankerOptions::default()
        };

        Ok((query, documents, options))
    }

    /// Build Protobuf RerankerResult from scoring result and args
    ///
    /// This method performs:
    /// 1. Score blending (original_score × (1-ratio) + reranking_score × ratio)
    /// 2. Score-based sorting (descending)
    /// 3. top_k filtering
    /// 4. score_threshold filtering
    /// 5. RankedCandidate generation with rank assignment
    fn build_result(
        args: &RerankerArgs,
        scoring_result: ScoringResult,
        reranker: &LlamaReranker,
        processing_time_ms: u64,
    ) -> Result<RerankerResult> {
        let scores = scoring_result.scores;
        let stats_data = scoring_result.stats;

        let cache_hits = stats_data.cache_hits;
        let cache_misses = stats_data.cache_misses;
        let cache_hit_rate = stats_data.cache_hit_rate;
        let truncated_count = stats_data.truncated_count;

        // 1. Score blending
        let blend_ratio = args
            .options
            .as_ref()
            .and_then(|o| o.score_blend_ratio)
            .unwrap_or(1.0);

        let final_scores: Vec<f32> = args
            .candidates
            .iter()
            .zip(&scores)
            .map(|(cand, &reranking_score)| {
                if let Some(original_score) = cand.original_score {
                    utils::blend_scores(original_score, reranking_score, blend_ratio)
                } else {
                    reranking_score
                }
            })
            .collect();

        // 2. Create indexed scores for sorting
        let mut indexed_scores: Vec<(usize, f32, f32)> = args
            .candidates
            .iter()
            .enumerate()
            .map(|(i, _)| (i, final_scores[i], scores[i]))
            .collect();

        // 3. Sort by final score (descending)
        indexed_scores.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

        // 4. Apply top_k filter
        if let Some(top_k) = args.options.as_ref().and_then(|o| o.top_k) {
            indexed_scores.truncate(top_k as usize);
        }

        // 5. Apply score_threshold filter
        if let Some(threshold) = args.options.as_ref().and_then(|o| o.score_threshold) {
            indexed_scores.retain(|(_, final_score, _)| *final_score >= threshold);
        }

        // 6. Generate RankedCandidate list
        let ranked_candidates: Vec<proto::RankedCandidate> = indexed_scores
            .iter()
            .enumerate()
            .map(
                |(rank, &(orig_idx, final_score, reranking_score))| proto::RankedCandidate {
                    reranking_score,
                    final_score,
                    rank: (rank + 1) as u32,
                    original_data: args.candidates[orig_idx].original_data.clone(),
                    original_score: args.candidates[orig_idx].original_score,
                    id: args.candidates[orig_idx].id.clone(),
                },
            )
            .collect();

        // 7. Build statistics
        let avg_time_per_candidate_ms = if !args.candidates.is_empty() {
            processing_time_ms as f32 / args.candidates.len() as f32
        } else {
            0.0
        };

        let stats = proto::RerankerStats {
            input_count: args.candidates.len() as u32,
            output_count: ranked_candidates.len() as u32,
            truncated_count: truncated_count as u32,
            cache_hits: cache_hits as u32,
            cache_misses: cache_misses as u32,
            cache_hit_rate,
            processing_time_ms,
            avg_time_per_candidate_ms,
            model_id: reranker.name().to_string(),
            device: reranker.device().to_string(),
        };

        Ok(RerankerResult {
            ranked_candidates,
            stats: Some(stats),
            success: true,
            error_message: None,
        })
    }
}

impl Default for RerankerRunnerPlugin {
    fn default() -> Self {
        Self::new()
    }
}

impl RerankerRunnerPlugin {
    fn load_sync(&mut self, settings: Vec<u8>) -> Result<()> {
        tracing::info!("Loading RerankerRunner plugin");

        let settings = RerankerSettings::decode(&mut Cursor::new(settings))?;
        let config = Self::parse_settings(settings)?;

        tracing::info!(
            "Initializing reranker: model={}, device={}, cache_size={}",
            config.model.model_id,
            if config.model.use_cpu { "CPU" } else { "GPU" },
            config.cache_size
        );

        // Initialize reranker (synchronous)
        let reranker = LlamaReranker::new(config.clone())?;

        self.config = Some(config);
        self.reranker = Some(Arc::new(reranker));

        tracing::info!("RerankerRunner loaded successfully");
        Ok(())
    }
}

/// Execute reranking for a single request. Pulled out of the trait method so
/// the returned future is `'static`. `token` is `None` when the host did not
/// register a cancellation token; the inner per-document loop simply skips
/// the cooperative-cancel check in that case.
async fn run_reranker(
    reranker: Arc<LlamaReranker>,
    arg: Vec<u8>,
    token: Option<CancelToken>,
) -> std::result::Result<Vec<u8>, String> {
    let start = Instant::now();

    let args = RerankerArgs::decode(&mut Cursor::new(arg))
        .map_err(|e| format!("Failed to decode args: {e}"))?;

    let (query, documents, options) =
        RerankerRunnerPlugin::parse_args(&args).map_err(|e| format!("Invalid arguments: {e}"))?;

    tracing::debug!(
        "Reranking {} documents for query: '{}'",
        documents.len(),
        query
    );

    let scoring_result = reranker
        .compute_scores_with_stats(&query, &documents, options, token.as_ref())
        .await
        .map_err(|e| match e {
            RerankerError::Cancelled => CANCELLED.to_string(),
            other => format!("Reranking failed: {other}"),
        })?;

    let processing_time_ms = start.elapsed().as_millis() as u64;

    tracing::info!(
        "Reranking completed: {} documents processed in {}ms (avg {:.1}ms/doc), cache hits: {}/{} ({:.1}%)",
        documents.len(),
        processing_time_ms,
        processing_time_ms as f32 / documents.len().max(1) as f32,
        scoring_result.stats.cache_hits,
        documents.len(),
        scoring_result.stats.cache_hit_rate * 100.0
    );

    let built =
        RerankerRunnerPlugin::build_result(&args, scoring_result, &reranker, processing_time_ms)
            .map_err(|e| format!("Failed to build result: {e}"))?;
    Ok(built.encode_to_vec())
}

#[async_trait::async_trait]
impl PluginV2 for RerankerRunnerPlugin {
    fn name(&self) -> String {
        Self::RUNNER_NAME.to_string()
    }

    fn description(&self) -> String {
        "Rerank text candidates using llama.cpp-based Qwen3-Reranker-4B-GGUF model".to_string()
    }

    fn runner_settings_proto(&self) -> String {
        include_str!("../protobuf/reranker_settings.proto").to_string()
    }

    fn method_proto_map(&self) -> HashMap<String, Vec<u8>> {
        static CACHED: std::sync::OnceLock<HashMap<String, Vec<u8>>> = std::sync::OnceLock::new();
        CACHED
            .get_or_init(|| {
                let mut m = HashMap::new();
                m.insert(
                    METHOD_RUN.to_string(),
                    MethodSchema {
                        args_proto: include_str!("../protobuf/reranker_args.proto").to_string(),
                        result_proto: include_str!("../protobuf/reranker_result.proto").to_string(),
                        description: Some("Rerank a set of candidates against a query".to_string()),
                        output_type: StreamingOutputType::NonStreaming as i32,
                        ..Default::default()
                    }
                    .encode_to_vec(),
                );
                m
            })
            .clone()
    }

    fn method_json_schema_map(&self) -> Option<HashMap<String, Vec<u8>>> {
        static CACHED: std::sync::OnceLock<HashMap<String, Vec<u8>>> = std::sync::OnceLock::new();
        Some(
            CACHED
                .get_or_init(|| {
                    let mut m = HashMap::new();
                    m.insert(
                        METHOD_RUN.to_string(),
                        MethodJsonSchema {
                            args_schema: json_schema_string::<RerankerArgs>("run_args_schema"),
                            result_schema: Some(json_schema_string::<RerankerResult>(
                                "run_result_schema",
                            )),
                            ..Default::default()
                        }
                        .encode_to_vec(),
                    );
                    m
                })
                .clone(),
        )
    }

    fn settings_schema(&self) -> String {
        json_schema_string::<RerankerSettings>("settings_schema")
    }

    fn set_cancellation_token(&mut self, token: CancelToken) {
        self.token = Some(token);
    }

    async fn load(&mut self, settings: Vec<u8>) -> std::result::Result<(), String> {
        self.load_sync(settings).map_err(|e| e.to_string())
    }

    async fn run(
        &mut self,
        arg: Vec<u8>,
        metadata: HashMap<String, String>,
        _using: Option<String>,
    ) -> (
        std::result::Result<Vec<u8>, String>,
        HashMap<String, String>,
    ) {
        let token = self.token.clone();
        let handle = self.rt_handle();
        let reranker = self.reranker.clone();

        // Honour cancellation even before the reranker is loaded so callers
        // get a consistent "cancelled" error regardless of plugin state.
        if token.as_ref().is_some_and(|t| t.is_cancelled()) {
            return (Err(CANCELLED.to_string()), metadata);
        }
        let result = match reranker {
            Some(reranker) => {
                // Clone the token for the spawned task; keep the original
                // around for the outer cancel-branch select.
                let token_for_inner = token.clone();
                let join = handle.spawn(run_reranker(reranker, arg, token_for_inner));
                // Await the inner task even if the outer token fires —
                // `run_reranker` observes the token at document boundaries
                // and exits with `RerankerError::Cancelled`, releasing model
                // resources before we return to the host. Without this join
                // the next job could find the reranker still busy.
                tokio::pin!(join);
                let joined = match token.as_ref() {
                    Some(t) => {
                        let cancel_branch = async {
                            t.cancelled().await;
                        };
                        tokio::pin!(cancel_branch);
                        tokio::select! {
                            biased;
                            _ = &mut cancel_branch => (&mut join).await,
                            j = &mut join => j,
                        }
                    }
                    None => (&mut join).await,
                };
                let cancel_observed = token.as_ref().is_some_and(|t| t.is_cancelled());
                match joined {
                    Ok(Ok(_)) if cancel_observed => Err(CANCELLED.to_string()),
                    Ok(Ok(bytes)) => Ok(bytes),
                    Ok(Err(_)) if cancel_observed => Err(CANCELLED.to_string()),
                    Ok(Err(e)) => Err(e),
                    Err(e) => Err(format!("join error: {e}")),
                }
            }
            None => Err("Reranker not loaded".to_string()),
        };
        (result, metadata)
    }

    async fn run_stream(
        &mut self,
        _args: Vec<u8>,
        _metadata: HashMap<String, String>,
        _using: Option<String>,
        _output: HighLevelSink,
    ) -> std::result::Result<HashMap<String, String>, String> {
        Err("streaming is not supported by reranker-runner".to_string())
    }
}

fn build_plugin_instance() -> RerankerRunnerPlugin {
    dotenvy::dotenv().ok();
    if let Ok(rt) = tokio::runtime::Runtime::new() {
        rt.block_on(async {
            command_utils::util::tracing::tracing_init_from_env()
                .await
                .unwrap_or_default();
        });
    }
    RerankerRunnerPlugin::new()
}

register_plugin_v2!(RerankerRunnerPlugin, build_plugin_instance());
