// Reranker Runner - llama.cpp-based reranker plugin for JobworkerP
//
// This module provides high-performance document reranking using llama.cpp
// and Qwen3-Reranker-4B-GGUF model, achieving 100-250x speedup over
// the existing Candle-based implementation.

use anyhow::{anyhow, Result};
use jobworkerp_client::{
    plugins::PluginRunner, schema_to_json_string, schema_to_json_string_option,
};
use prost::Message;
use std::{collections::HashMap, io::Cursor, sync::Arc, time::Instant};

// Shared components (copied from search-runner)
pub mod cache;
pub mod traits;
pub mod utils;

// Core components
pub mod config;
pub mod error;
pub mod model;
pub mod reranker;

// Protocol Buffers (generated by build.rs)
pub mod proto {
    tonic::include_proto!("reranker_runner");
}

// Re-export commonly used types
pub use cache::RerankerCache;
pub use config::{RerankerConfig, RerankerModelConfig};
pub use error::RerankerError;
pub use model::LlamaRerankerModel;
pub use reranker::{LlamaReranker, ScoringResult, ScoringStats};
pub use traits::{DocumentReranker, RerankerOptions};
pub use utils::{blend_scores, generate_cache_key};

use proto::{RerankerArgs, RerankerResult, RerankerSettings};

/// RerankerRunner Plugin for JobworkerP
///
/// This plugin provides document reranking functionality using llama.cpp
/// and Qwen3-Reranker-4B-GGUF model.
pub struct RerankerRunnerPlugin {
    /// Tokio runtime for async operations
    rt: Arc<tokio::runtime::Runtime>,
    /// Reranker instance (initialized in load())
    reranker: Option<LlamaReranker>,
    /// Configuration
    config: Option<RerankerConfig>,
}

impl RerankerRunnerPlugin {
    pub const RUNNER_NAME: &str = "RerankerRunner";

    pub fn new() -> Self {
        let rt = Arc::new(tokio::runtime::Runtime::new().expect("Failed to create Tokio runtime"));
        Self {
            rt,
            reranker: None,
            config: None,
        }
    }

    /// Parse Protobuf RerankerSettings into RerankerConfig
    fn parse_settings(settings: RerankerSettings) -> Result<RerankerConfig> {
        let model = RerankerModelConfig {
            model_id: settings.model_id,
            hf_repo: settings.hf_repo.unwrap_or_default(),
            use_cpu: settings.use_cpu,
            threads: settings.threads.map(|t| t as usize).unwrap_or(4),
            ctx_size: settings.ctx_size.map(|c| c as usize).unwrap_or(32768),
            n_batch: settings.n_batch.map(|b| b as usize).unwrap_or(32768),
            use_flash_attention: settings.use_flash_attention.unwrap_or(true),
            default_instruction: settings.default_instruction,
            max_document_length_gpu: settings
                .max_document_length_gpu
                .map(|m| m as usize)
                .unwrap_or(20_000),
            max_document_length_cpu: settings
                .max_document_length_cpu
                .map(|m| m as usize)
                .unwrap_or(5_000),
        };

        Ok(RerankerConfig {
            model,
            cache_size: settings.cache_size.map(|c| c as usize).unwrap_or(10_000),
            cache_ttl_seconds: settings.cache_ttl_seconds.unwrap_or(3600),
        })
    }

    /// Parse Protobuf RerankerArgs into (query, documents, options)
    fn parse_args(args: &RerankerArgs) -> Result<(String, Vec<String>, RerankerOptions)> {
        let query = args.query.clone();

        if query.is_empty() {
            return Err(anyhow!("Query is empty"));
        }

        // Extract text from candidates
        let documents: Vec<String> = args.candidates.iter().map(|c| c.text.clone()).collect();

        if documents.is_empty() {
            return Err(anyhow!("No candidates provided"));
        }

        // Parse options
        let options = if let Some(opts) = &args.options {
            RerankerOptions {
                top_k: opts.top_k.map(|k| k as usize),
                score_threshold: opts.score_threshold,
                instruction: opts.instruction.clone(),
                batch_size: opts.batch_size.map(|b| b as usize).unwrap_or(1),
                use_cache: opts.use_cache.unwrap_or(true),
                max_document_length: opts.max_document_length.map(|m| m as usize),
            }
        } else {
            RerankerOptions::default()
        };

        Ok((query, documents, options))
    }

    /// Build Protobuf RerankerResult from scoring result and args
    ///
    /// This method performs:
    /// 1. Score blending (original_score × (1-ratio) + reranking_score × ratio)
    /// 2. Score-based sorting (descending)
    /// 3. top_k filtering
    /// 4. score_threshold filtering
    /// 5. RankedCandidate generation with rank assignment
    fn build_result(
        args: &RerankerArgs,
        scoring_result: ScoringResult,
        reranker: &LlamaReranker,
        processing_time_ms: u64,
    ) -> Result<RerankerResult> {
        let scores = scoring_result.scores;
        let stats_data = scoring_result.stats;

        let cache_hits = stats_data.cache_hits;
        let cache_misses = stats_data.cache_misses;
        let cache_hit_rate = stats_data.cache_hit_rate;
        let truncated_count = stats_data.truncated_count;

        // 1. Score blending
        let blend_ratio = args
            .options
            .as_ref()
            .and_then(|o| o.score_blend_ratio)
            .unwrap_or(1.0);

        let final_scores: Vec<f32> = args
            .candidates
            .iter()
            .zip(&scores)
            .map(|(cand, &reranking_score)| {
                if let Some(original_score) = cand.original_score {
                    utils::blend_scores(original_score, reranking_score, blend_ratio)
                } else {
                    reranking_score
                }
            })
            .collect();

        // 2. Create indexed scores for sorting
        let mut indexed_scores: Vec<(usize, f32, f32)> = args
            .candidates
            .iter()
            .enumerate()
            .map(|(i, _)| (i, final_scores[i], scores[i]))
            .collect();

        // 3. Sort by final score (descending)
        indexed_scores.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

        // 4. Apply top_k filter
        if let Some(top_k) = args.options.as_ref().and_then(|o| o.top_k) {
            indexed_scores.truncate(top_k as usize);
        }

        // 5. Apply score_threshold filter
        if let Some(threshold) = args.options.as_ref().and_then(|o| o.score_threshold) {
            indexed_scores.retain(|(_, final_score, _)| *final_score >= threshold);
        }

        // 6. Generate RankedCandidate list
        let ranked_candidates: Vec<proto::RankedCandidate> = indexed_scores
            .iter()
            .enumerate()
            .map(
                |(rank, &(orig_idx, final_score, reranking_score))| proto::RankedCandidate {
                    reranking_score,
                    final_score,
                    rank: (rank + 1) as u32,
                    original_data: args.candidates[orig_idx].original_data.clone(),
                    original_score: args.candidates[orig_idx].original_score,
                    id: args.candidates[orig_idx].id.clone(),
                },
            )
            .collect();

        // 7. Build statistics
        let avg_time_per_candidate_ms = if !args.candidates.is_empty() {
            processing_time_ms as f32 / args.candidates.len() as f32
        } else {
            0.0
        };

        let stats = proto::RerankerStats {
            input_count: args.candidates.len() as u32,
            output_count: ranked_candidates.len() as u32,
            truncated_count: truncated_count as u32,
            cache_hits: cache_hits as u32,
            cache_misses: cache_misses as u32,
            cache_hit_rate,
            processing_time_ms,
            avg_time_per_candidate_ms,
            model_id: reranker.name().to_string(),
            device: reranker.device().to_string(),
        };

        Ok(RerankerResult {
            ranked_candidates,
            stats: Some(stats),
            success: true,
            error_message: None,
        })
    }
}

impl Default for RerankerRunnerPlugin {
    fn default() -> Self {
        Self::new()
    }
}

impl PluginRunner for RerankerRunnerPlugin {
    fn name(&self) -> String {
        Self::RUNNER_NAME.to_string()
    }

    fn description(&self) -> String {
        "Rerank text candidates using llama.cpp-based Qwen3-Reranker-4B-GGUF model".to_string()
    }

    fn load(&mut self, settings: Vec<u8>) -> Result<()> {
        tracing::info!("Loading RerankerRunner plugin");

        let settings = RerankerSettings::decode(&mut Cursor::new(settings))?;
        let config = Self::parse_settings(settings)?;

        tracing::info!(
            "Initializing reranker: model={}, device={}, cache_size={}",
            config.model.model_id,
            if config.model.use_cpu { "CPU" } else { "GPU" },
            config.cache_size
        );

        // Initialize reranker (synchronous)
        let reranker = LlamaReranker::new(config.clone())?;

        self.config = Some(config);
        self.reranker = Some(reranker);

        tracing::info!("RerankerRunner loaded successfully");
        Ok(())
    }

    fn run(
        &mut self,
        arg: Vec<u8>,
        _metadata: HashMap<String, String>,
    ) -> (Result<Vec<u8>>, HashMap<String, String>) {
        let start = Instant::now();

        // Decode args
        let args = match RerankerArgs::decode(&mut Cursor::new(arg)) {
            Ok(args) => args,
            Err(e) => {
                tracing::error!("Failed to decode args: {}", e);
                let err_result = RerankerResult {
                    success: false,
                    error_message: Some(format!("Failed to decode args: {}", e)),
                    stats: None,
                    ranked_candidates: vec![],
                };
                return (Ok(err_result.encode_to_vec()), HashMap::new());
            }
        };

        // Parse args
        let (query, documents, options) = match Self::parse_args(&args) {
            Ok(parsed) => parsed,
            Err(e) => {
                tracing::error!("Failed to parse args: {}", e);
                let err_result = RerankerResult {
                    success: false,
                    error_message: Some(format!("Invalid arguments: {}", e)),
                    stats: None,
                    ranked_candidates: vec![],
                };
                return (Ok(err_result.encode_to_vec()), HashMap::new());
            }
        };

        tracing::debug!(
            "Reranking {} documents for query: '{}'",
            documents.len(),
            query
        );

        // Get reranker
        let reranker = match self.reranker.as_mut() {
            Some(r) => r,
            None => {
                tracing::error!("Reranker not initialized");
                let err_result = RerankerResult {
                    success: false,
                    error_message: Some("Reranker not loaded".to_string()),
                    stats: None,
                    ranked_candidates: vec![],
                };
                return (Ok(err_result.encode_to_vec()), HashMap::new());
            }
        };

        // Execute reranking (async operation with blocking)
        let rt = self.rt.clone();
        let result = rt.block_on(async {
            reranker
                .compute_scores_with_stats(&query, &documents, options)
                .await
        });

        match result {
            Ok(scoring_result) => {
                let processing_time_ms = start.elapsed().as_millis() as u64;

                tracing::info!(
                    "Reranking completed: {} documents processed in {}ms (avg {:.1}ms/doc), cache hits: {}/{} ({:.1}%)",
                    documents.len(),
                    processing_time_ms,
                    processing_time_ms as f32 / documents.len() as f32,
                    scoring_result.stats.cache_hits,
                    documents.len(),
                    scoring_result.stats.cache_hit_rate * 100.0
                );

                // Build result with score blending and filtering
                match Self::build_result(&args, scoring_result, reranker, processing_time_ms) {
                    Ok(result) => (Ok(result.encode_to_vec()), HashMap::new()),
                    Err(e) => {
                        tracing::error!("Failed to build result: {}", e);
                        let err_result = RerankerResult {
                            success: false,
                            error_message: Some(format!("Failed to build result: {}", e)),
                            stats: None,
                            ranked_candidates: vec![],
                        };
                        (Ok(err_result.encode_to_vec()), HashMap::new())
                    }
                }
            }
            Err(e) => {
                tracing::error!("Reranking failed: {}", e);
                let err_result = RerankerResult {
                    success: false,
                    error_message: Some(format!("Reranking failed: {}", e)),
                    stats: None,
                    ranked_candidates: vec![],
                };
                (Ok(err_result.encode_to_vec()), HashMap::new())
            }
        }
    }

    fn cancel(&self) -> bool {
        // Phase 1: Cancellation not supported
        false
    }

    fn is_canceled(&self) -> bool {
        false
    }

    fn runner_settings_proto(&self) -> String {
        include_str!("../protobuf/reranker_settings.proto").to_string()
    }

    fn job_args_proto(&self) -> String {
        include_str!("../protobuf/reranker_args.proto").to_string()
    }

    fn result_output_proto(&self) -> Option<String> {
        Some(include_str!("../protobuf/reranker_result.proto").to_string())
    }

    fn settings_schema(&self) -> String {
        schema_to_json_string!(RerankerSettings, "settings_schema")
    }

    fn arguments_schema(&self) -> String {
        schema_to_json_string!(RerankerArgs, "arguments_schema")
    }

    fn output_json_schema(&self) -> Option<String> {
        schema_to_json_string_option!(RerankerResult, "output_json_schema")
    }
}

// C API exports for dynamic plugin loading
#[cfg(feature = "c-api")]
mod plugin_exports {
    use super::*;

    #[allow(improper_ctypes_definitions)]
    #[no_mangle]
    pub extern "C" fn load_plugin() -> Box<dyn PluginRunner + Send + Sync> {
        std::panic::catch_unwind(|| {
            // Load environment variables
            dotenvy::dotenv().ok();

            // Initialize tracing (synchronously)
            let runtime = tokio::runtime::Runtime::new()
                .expect("Failed to create Tokio runtime for tracing init");
            runtime.block_on(async {
                command_utils::util::tracing::tracing_init_from_env()
                    .await
                    .unwrap_or_default();
            });

            Box::new(RerankerRunnerPlugin::new()) as Box<dyn PluginRunner + Send + Sync>
        })
        .unwrap_or_else(|e| {
            eprintln!("load_plugin panic: {:?}", e);
            Box::new(RerankerRunnerPlugin::new())
        })
    }

    #[no_mangle]
    #[allow(improper_ctypes_definitions)]
    pub extern "C" fn free_plugin(ptr: Box<dyn PluginRunner + Send + Sync>) {
        drop(ptr);
    }
}
